version: '3.4'

x-common-variables: &shared-vars
  MONGO_PORT: tcp://db:27017
  SPRING_DATA_MONGODB_USERNAME: ${MONGO_HYG_USER}
  SPRING_DATA_MONGODB_PASSWORD: ${MONGO_HYG_PW}
  #API_HOST: api
  
x-common-variables: &gitlab-vars
  GITLAB_HOST: gitlab.test
  GITLAB_PORT: 80
  GITLAB_API_TOKEN: ${GITLAB_API_TOKEN}

x-common-variables: &jenkins-vars
  JENKINS_NAME: Test Jenkins
  JENKINS_MASTER: http://jenkins.test:802
  JENKINS_USERNAME: hygieia
  JENKINS_API_KEY: ${JENKINS_API_KEY}

x-common-variables: &bitbucket-vars
  BITBUCKET_HOST: bitbucket.org/yourinstance/
  BITBUCKET_KEY: ${BITBUCKET_SSH_KEY}
  
x-common-variables: &github-vars
  PERSONAL_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

x-common-variables: &mongo-vars
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PW}

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      <<: *mongo-vars
    volumes:
      - "./data/mongo_config:/data/configdb"
      - "./data/mongo_data:/data/db"
        
  db-setup:
    build: ../../built/db
    environment:
      <<: *shared-vars
      <<: *mongo-vars
    depends_on:
      - db
      
  api:
    build: ../../built/api
    image: hygieia-api
    depends_on:
      - db-setup
    ports:
      - "8080:8080"
    environment:
      <<: *shared-vars
      #AUTH_SECRET: somesecret
    volumes:
      - "./data/mongo_data:/data/db"
      - "./logs:/hygieia/logs"
  
  api-audit:
    build: ../../built/api-audit
    image: hygieia-api-audit
    depends_on:
      - db-setup
    ports:
      - "8081:8080"
  
  ui:
    build: ../../built/UI
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      <<: *shared-vars
    
  # bitbucket-collector:
  #   build: ../../built/collector-bitbucket-scm
  #   image: hygieia-bitbucket-scm-collector
  #   depends_on:
  #     - db-setup
  #   environment:
  #     <<: *shared-vars
  #     <<: *bitbucket-vars
  
  github-collector:
    build: ../../built/collector-github-scm
    image: hygieia-github-scm-collector
    depends_on:
      - db-setup
    environment:
      <<: *shared-vars
      <<: *github-vars

  # gitlab-feature-collector:
  #   build: ../../built/collector-gitlab-feature
  #   image: hygieia-gitlab-feature-collector
  #   depends_on:
  #     - db-setup
  #   environment:
  #     <<: *shared-vars
  #     <<: *gitlab-vars
  #   #networks:
  #   #  - default
  #   #  - gitlab_default
      
  # gitlab-scm-collector:
  #   build: ../../built/collector-gitlab-scm
  #   image: hygieia-gitlab-scm-collector
  #   depends_on:
  #     - db-setup
  #   environment:
  #     <<: *shared-vars
  #   #networks:
  #   #  - default
  #   #  - gitlab_default

  # jenkins-build-collector:
  #   build: ../../built/collector-jenkins-build
  #   image: hygieia-jenkins-build-collector
  #   depends_on:
  #     - db-setup
  #   environment:
  #     <<: *shared-vars
  #     <<: *jenkins-vars
  #   #networks:
  #   #  - default
  #   #  - jenkins_default

  # jenkins-codequality-collector:
  #   build: ../../built/collector-jenkins-codequality
  #   image: hygieia-jenkins-codequality-collector
  #   depends_on:
  #     - db-setup
  #   environment:
  #     <<: *shared-vars
  #     <<: *jenkins-vars
  #   #networks:
  #   #  - default
  #   #  - jenkins_default

  # gitlab_default:
  #   external: true
  # jenkins_default:
  #   external: true
      
volumes:
  certs: